### ISSUE TITLE
Correcting Text Colors for Calender

### ISSUE THREAD

**Issue by Binit06** [Binit06/Club_Event_Manager#9]
**The colors of the text are not visible for chrome in some themes. Make the colors of the text clear.**

![image](https://github.com/Binit06/Club_Event_Manager/assets/128616465/1768a7a2-2aaf-4ccf-bd7d-ea2430230c6e)

Please fix this......

To install all modules:
` npm install `

**Comment by ISOHAN07** [comment]
I will be working on this issue
